# Services
services:
  # Apache + PHP
  apache_php-cont:
    build:
      context: ./.docker
      dockerfile: Dockerfile
    container_name: apache_php-cont
    # Preparamos un volumen para almacenar nuestro cÃ³digo
    volumes:
      - ./varwwwhtml/:/var/www/html
      - ./.docker/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini-development
      - .docker/xdebug/debug.ini:/usr/local/etc/php/conf.d/debug.ini
    expose:
      - 80
      - 8000
    ports:
      - 8081:80
      - 8000:8000
    networks:
      - todored
    links:
      - basemariadb
      - mongo-cont
      - redis-cont
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"
    #user: "1002:1002" # IMPORTANTE: UID:GID     (id -u ; id -g)
    #user: ${whoami}:${whoami} #ciclost:ciclost
    command: >
      bash -c "chmod -R 0777 /var/www/html && apache2-foreground"
    #depends_on:
    #  - basemariadb
        #condition: service_healthy


  basemariadb:
    image: mariadb:latest
    restart: on-failure
    ports:
      - 3310:3306
    networks:
      - todored
    volumes:
      - ./.docker/mariadb:/var/lib/mysql:Z
    env_file: "./.docker/.env"
    command: ["--default-authentication-plugin=mysql_native_password"]
    

  mongo-cont:
    image: mongo
    restart: on-failure
    env_file: "./.docker/.env"
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: 123456789
    networks:
     - todored
    ports:
      - 27018:27017
    #user: "1002:1002" # IMPORTANTE: UID:GID     (id -u ; id -g)

  redis-cont:
    image: redis:latest
    volumes:
        - .docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    #    - ./.docker/redis/data:/data
    ports:
      - 6380:6379
    networks:
      - todored
    #command: ["redis-server", "/usr/local/etc/redis/redis.conf"]


networks:
  todored:
    name: todored
    driver: bridge

